# Write a function so that the columns of the output matrix are powers of the input vector. The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.
# HINT: Such a matrix with a geometric progression in each row is named for Alexandre- Theophile Vandermonde.

In [2]:
import numpy as np

In [38]:
############ Citation reference from numpy docs -> https://numpy.org/doc/stable/reference/generated/numpy.vander.html

def op_matrix(x,N,check):
    if not check:
        opt=np.column_stack([x**i for i in range(N)])
    else:
        opt=np.column_stack([x**(N-1-i) for i in range(N)])
    return(opt)

In [39]:
inp_list=[]
print("Enter number of elements  of input vectors")
N=int(input())
for i in range(N):
    inp=int(input())
    inp_list.append(inp)

######     converting to nd Array 
inp_vec=np.asarray(inp_list)
print("Input Vector->",inp_vec)

print("Enter number of columns to be in Matrix")
col=int(input())

op_matrix_inc = op_matrix(inp_vec,col,False)
op_matrix_dec = op_matrix(inp_vec,col,True)

print("Increasing order:\n\n",op_matrix_inc,"\n")
print("Decreasing order :\n\n",op_matrix_dec,"\n")

Enter number of elements  of input vectors
3
1
2
3
Input Vector-> [1 2 3]
Enter number of columns to be in Matrix
3
Increasing order:

 [[1 1 1]
 [1 2 4]
 [1 3 9]] 

Decreasing order :

 [[1 1 1]
 [4 2 1]
 [9 3 1]] 



# Write a function to find moving average in an array over a window:
# Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.



In [78]:
# Input array in form of numpy array
x = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
# defiing a list to store result of moving averages
res_avg=list()
k=3

op_len=x.size

# defining two points : first is pointing to first element in window and last will be pointing to end of the element in window.
# defining a window variable which takes a slice of input array starting from pointer "first" to "last" pointer
# Everytime loop variable increase the step size increases and selects next three times at a time.
# Window is a numpy array and mean is predefined function in numpy and it gives mean of that window.
# storing each moving average in res_avg list
# finally converting list to numpy array and printed
for first in range(op_len):
    last=first+k
    if last>len(x):
        break
    window=np.take(x,range(first,last))
    res_avg.append(window.mean())
    

y=np.asarray(res_avg)
print(y)

[  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]
